- name: playbook for dispatch
  hosts: dispatch
  become: yes
  tasks:
  - name: Install GoLang
    ansible.builtin.package:
      name: golang
      state: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop

  - name: remove app directory if already present
    ansible.builtin.file:
      path: /app
      state: absent

  - name: setup an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code to created app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp

  - name: unzip code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: Lets download the dependencies & build the software
    ansible.builtin.shell: cd /app ; go mod init dispatch; go get ; go build

  - name: Setup SystemD Dispatch Service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: Load the service
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: Start the service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes
