- name: mysql playbook
  hosts: mysql
  become: yes
  tasks:
  - name: disable MySQL 8 versio
    ansible.builtin.shell: dnf module disable mysql -y

  - name: Setup the MySQL5.7 repo file
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL Server
    ansible.builtin.package:
      name: mysql-community-server
      state: present 

  - name: Start MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: change the default root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

  - name: check the new password working or not
    ansible.builtin.shell: mysql -uroot -pRoboShop@1