- name: playbook for shipping
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
  - name: Maven install
    ansible.builtin.package:
      name: maven
      state: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop

  - name: remove app directory if already present
    ansible.builtin.file:
      path: /app
      state: absent

  - name: setup an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp
  
  - name: unzip application to created app directory
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: download the dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move application code
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: Setup SystemD Shipping Service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Load the service
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: Start the service
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: install mysql client
    ansible.builtin.package:
      name: mysql 
      state: present 

  - name: check cities schema exists or not
    ansible.builtin.command: .command:  mysql -h mysql.daws76s.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'c
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"
  
  - name: load schema
    ansible.builtin.shell: mysql -h mysql.kiranku.online -uroot -p{{mysql_passsword}} < /app/schema/shipping.sql 
    when: schema.stdout == "0"

  - name: restart the service
    ansible.builtin.service:
      name: shipping
      state: restarted