- name: user playbook
  hosts: user
  become: yes
  tasks:
  - name: Install NodeJS, enable 18 version and install
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs 
      state: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop

  - name: remove app directory if already present
    ansible.builtin.file:
      path: /app
      state: absent

  - name: setup an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the application code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
      
  - name: unzip application to created app directory
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: download the dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: Setup SystemD user Service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes

  - name: setup the mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: get the categories count
    ansible.builtin.command: mongo --host mongodb.kiranku.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: print the count
    ansible.builtin.debug:
      msg: "user count: {{user_count}}"

  - name: load user data
    ansible.builtin.shell: mongo --host mongodb.kiranku.online </app/schema/user.js
    when: user_count.stdout == "0"

  - name: Start and enable the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes